services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: SPB_Backend_Blog
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL : jdbc:postgresql://host.docker.internal:8181/postgres
      SPRING_DATASOURCE_USERNAME : postgres
      SPRING_DATASOURCE_PASSWORD : s3cretpass
      SPRING_DATASOURCE_DB: postgres_db

